version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ergovision-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ergovision-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: